### ISSUE TITLE
Fix broken travis build

### ISSUE THREAD

**Issue by mistadikay** [yummies/yummies#2]
When running coverage npm script locally on `node@4.0.0` everything is fine. On Travis under `iojs@3.3.0` it is breaking with error:
```
/home/travis/build/yummies/yummies/node_modules/isparta/lib/cli.js:197
    _istanbul.hook.hookRequire(matchFn, transformer, Object.assign({ verbose: opts.verbose }, config.instrumentation.config));
                                                            ^
TypeError: Object.assign is not a function
    at prepareCoverage (/home/travis/build/yummies/yummies/node_modules/isparta/lib/cli.js:197:61)
    at /home/travis/build/yummies/yummies/node_modules/isparta/lib/cli.js:187:7
    at /home/travis/build/yummies/yummies/node_modules/isparta/node_modules/istanbul/lib/util/file-matcher.js:68:16
    at /home/travis/build/yummies/yummies/node_modules/isparta/node_modules/istanbul/node_modules/async/lib/async.js:52:16
    at /home/travis/build/yummies/yummies/node_modules/isparta/node_modules/istanbul/node_modules/async/lib/async.js:363:13
    at /home/travis/build/yummies/yummies/node_modules/isparta/node_modules/istanbul/node_modules/async/lib/async.js:52:16
    at done (/home/travis/build/yummies/yummies/node_modules/isparta/node_modules/istanbul/node_modules/async/lib/async.js:248:21)
    at /home/travis/build/yummies/yummies/node_modules/isparta/node_modules/istanbul/node_modules/async/lib/async.js:44:16
    at /home/travis/build/yummies/yummies/node_modules/isparta/node_modules/istanbul/node_modules/async/lib/async.js:360:17
    at LOOP (fs.js:1529:14)
```

**Comment by mistadikay** [comment]
My first glue was missing runtime, but it is there — both in `package.json` and `.babelrc`

**Comment by deepsweet** [comment]
https://github.com/douglasduteil/isparta/pull/64
